pages:
  stage: deploy
  script:
    - mkdir public
    - cp *.json *.png *.mp3 index.html COPYRIGHT public
    - sed -i
      -e 's/{<jitsiUrl>}/meet.jit.si/g'
      public/*.json
  artifacts:
    paths:
      - public
  only:
    - master
